### ISSUE TITLE
Heroku?

### ISSUE THREAD

**Issue by wabiloo** [drizzleco/create-flask-app#9]
Hi,
I selected the Heroku option in the form, but I don't see anything specific to Heroku deployment being enabled. Am I missing something?

**Comment by petabite** [comment]
Hello. Choosing the Heroku option should create a `Procfile` and `runtime.txt`.

**Comment by wabiloo** [comment]
Thanks, I probably thought I'd activated it, but failed.
Note: python-3.8.3 is not supported anymore on Heroku

**Comment by wabiloo** [comment]
It seems that you're also missing adding `gunicorn` in the requirements.txt

**Comment by petabite** [comment]
All good. Ah, thanks for the catch.
